# Lib RayTracing

This library is one of the filters of VCity project and has for purpose to perform raytracing algorithm on a list of Triangles and to return the intersections found.

## Dependencies

This library is linked against two other libraries :

- **OpenSceneGraph** (OSG). (External library)
- **Lib CityGML Utils**. (Documentation can be find in ... )

## Main Functionalities


### Test intersection between a ray and a triangle

You might need to test the intersection between a ray and a triangle. In order to achieve this, you can do as follow :

- Construct a **Ray**

A Ray can be build using the main constructor by giving the origin and the direction of the ray or using the following function:

	 void BuildRd(TVec2d fragCoord,osg::Camera* cam);

*Note: The function above can be useful when performing raytracing for rendering purposes, in which case you might need to construct a ray depending on a camera and the fragment coordinate corresponding to the ray.*

- Use the **Instersect** method of the ray :

		bool Intersect(Triangle* triangle, Hit* hit = nullptr);

This method will return true if there is an intersection and false otherwise.

The first parameter is the triangle to test the intersection with and is of type Triangle (libCityGML Utils).

The second parameter is a Hit and holds informations about the intersection such as the triangle that was hit and the hit position. All needed informations about this class can be found in the doxygen documentation.

### Perform RayTracing algorithm

The library also gives you the possibily of performing raytracing algorithm on a set of triangles with the following function of RayTracing.cpp :

	std::vector<Hit*> *RayTracing(TriangleList* triangles, std::vector<Ray*> rays);

This function will return a vector of Hit listing all intersections found between the rays and the triangles given in parameter.

The TriangleList must be build using LibCityGML Utils.

The vector of Ray can either be build manually or by creating a RayCollection variable which holds a vector of Ray and a method to fill it with all the rays generated by a camera.
The RayCollection structure is located in Ray.hpp and the method to build the vector of Ray is the following:

	static RayCollection* BuildCollection(osg::Camera* cam);

Once this function as been called, you can use the member 'rays' of the RayCollection struct to perform the raytracing algorithm.

*Note: This function is meant to ease construction of the vector of Ray when performing raytracing algorithm for rendering purposes.*


## RayTracing algortihm

Maybe ?


## Workflow ?

Maybe ?
