if (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER "19")
  message( "-- VCITY windows binary kit version:: VS2015")
  include("${CMAKE_SOURCE_DIR}/cmake/msvc/kit_vs2015-64_v01-common.cmake")
  if( DEFINED ENV{APPVEYOR} )
    message("   Loading AppVeyor specific variables for VS2015 KIT")
    include("${CMAKE_SOURCE_DIR}/cmake/msvc/kit_vs2015-64_v01-AppVeyor.cmake")
  else()
    message("   Loading desktop specific variables for VS2015 KIT")
    include("${CMAKE_SOURCE_DIR}/cmake/msvc/kit_vs2015-64_v01-desktop.cmake")
  endif()
elseif( CMAKE_CXX_COMPILER_VERSION VERSION_GREATER "17" )
  message( "-- VCITY windows binary kit version:: VS2012.")
  message( "   Warning: VS2012 kit is DEPRECATED...")
  include( "${CMAKE_SOURCE_DIR}/cmake/msvc/kit_vs2012-64_v08.cmake" )
endif()
